project:
  type: website
  output-dir: docs

website:
  title: "Shuyang's website"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: projects.qmd 
        text: Projects 
      - href: blogs.qmd 
        text: Blog 
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



